/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "surface-container-highest": "#dfdcdc",
                "secondary": "#6249b2",
                "on-secondary-container": "#4e339c",
                "on-tertiary": "#ffeff4",
                "error-dim": "#a70138",
                "tertiary-fixed": "#fd8bca",
                "error": "#b41340",
                "surface": "#f9f6f5",
                "on-secondary-fixed-variant": "#573da6",
                "on-primary-fixed-variant": "#1a0099",
                "inverse-on-surface": "#9e9c9c",
                "tertiary-fixed-dim": "#ee7ebc",
                "surface-tint": "#4a40e0",
                "on-background": "#2f2e2e",
                "inverse-primary": "#8582ff",
                "tertiary-container": "#fd8bca",
                "tertiary": "#983772",
                "surface-container-high": "#e5e2e1",
                "on-tertiary-fixed-variant": "#6d104e",
                "surface-dim": "#d6d4d3",
                "primary-fixed-dim": "#8885ff",
                "on-tertiary-container": "#610244",
                "surface-container-low": "#f3f0ef",
                "tertiary-dim": "#892a65",
                "on-surface-variant": "#5c5b5b",
                "on-error-container": "#510017",
                "secondary-dim": "#563ca5",
                "primary-dim": "#3d30d4",
                "surface-variant": "#dfdcdc",
                "outline-variant": "#afacac",
                "on-error": "#ffefef",
                "on-primary-container": "#14007e",
                "on-secondary": "#f7f0ff",
                "secondary-container": "#d8caff",
                "on-primary-fixed": "#000000",
                "surface-container-lowest": "#ffffff",
                "secondary-fixed": "#d8caff",
                "inverse-surface": "#0e0e0e",
                "on-primary": "#f4f1ff",
                "on-tertiary-fixed": "#360024",
                "primary": "#4a40e0",
                "outline": "#787676",
                "surface-container": "#eae7e7",
                "primary-container": "#9795ff",
                "primary-fixed": "#9795ff",
                "error-container": "#f74b6d",
                "surface-bright": "#f9f6f5",
                "on-secondary-fixed": "#3a1b88",
                "background": "#f9f6f5",
                "on-surface": "#2f2e2e",
                "secondary-fixed-dim": "#cbbaff"
            },
            fontFamily: {
                "headline": ["Plus Jakarta Sans", "sans-serif"],
                "body": ["Manrope", "sans-serif"],
                "label": ["Manrope", "sans-serif"]
            },
        },
    },
    plugins: [],
}
